// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: metadata.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CyberLife.Protobuff.Metadata {

  /// <summary>Holder for reflection information generated from metadata.proto</summary>
  public static partial class MetadataReflection {

    #region Descriptor
    /// <summary>File descriptor for metadata.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MetadataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5tZXRhZGF0YS5wcm90bxIcQ3liZXJMaWZlLlByb3RvYnVmZi5NZXRhZGF0",
            "YRoLcGxhY2UucHJvdG8aDW1hcFNpemUucHJvdG8iLAoNU3RhdGVNZXRhZGF0",
            "YRIMCgRuYW1lGAEgASgJEg0KBXZhbHVlGAIgASgBIksKEFBoZW5vbWVuTWV0",
            "YWRhdGESDAoEbmFtZRgBIAEoCRIpCgVwbGFjZRgCIAEoCzIaLkN5YmVyTGlm",
            "ZS5Qcm90b2J1ZmYuUGxhY2UijgEKEExpZmVGb3JtTWV0YWRhdGESKQoFcGxh",
            "Y2UYASABKAsyGi5DeWJlckxpZmUuUHJvdG9idWZmLlBsYWNlEgoKAmlkGAIg",
            "ASgDEkMKDnN0YXRlc01ldGFkYXRhGAMgAygLMisuQ3liZXJMaWZlLlByb3Rv",
            "YnVmZi5NZXRhZGF0YS5TdGF0ZU1ldGFkYXRhIo8BChNFbnZpcm9ubWVudE1l",
            "dGFkYXRhEi0KB21hcFNpemUYASABKAsyHC5DeWJlckxpZmUuUHJvdG9idWZm",
            "Lk1hcFNpemUSSQoRcGhlbm9tZW5hTWV0YWRhdGEYAiADKAsyLi5DeWJlckxp",
            "ZmUuUHJvdG9idWZmLk1ldGFkYXRhLlBoZW5vbWVuTWV0YWRhdGEiwAIKDVdv",
            "cmxkTWV0YWRhdGESTgoTZW52aXJvbm1lbnRNZXRhZGF0YRgBIAEoCzIxLkN5",
            "YmVyTGlmZS5Qcm90b2J1ZmYuTWV0YWRhdGEuRW52aXJvbm1lbnRNZXRhZGF0",
            "YRJbChBMaWZlRm9ybU1ldGFkYXRhGAIgAygLMkEuQ3liZXJMaWZlLlByb3Rv",
            "YnVmZi5NZXRhZGF0YS5Xb3JsZE1ldGFkYXRhLkxpZmVGb3JtTWV0YWRhdGFF",
            "bnRyeRIMCgRuYW1lGAMgASgJEgsKA2FnZRgEIAEoBRpnChVMaWZlRm9ybU1l",
            "dGFkYXRhRW50cnkSCwoDa2V5GAEgASgDEj0KBXZhbHVlGAIgASgLMi4uQ3li",
            "ZXJMaWZlLlByb3RvYnVmZi5NZXRhZGF0YS5MaWZlRm9ybU1ldGFkYXRhOgI4",
            "AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CyberLife.Protobuff.PlaceReflection.Descriptor, global::CyberLife.Protobuff.MapSizeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CyberLife.Protobuff.Metadata.StateMetadata), global::CyberLife.Protobuff.Metadata.StateMetadata.Parser, new[]{ "Name", "Value" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CyberLife.Protobuff.Metadata.PhenomenMetadata), global::CyberLife.Protobuff.Metadata.PhenomenMetadata.Parser, new[]{ "Name", "Place" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CyberLife.Protobuff.Metadata.LifeFormMetadata), global::CyberLife.Protobuff.Metadata.LifeFormMetadata.Parser, new[]{ "Place", "Id", "StatesMetadata" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CyberLife.Protobuff.Metadata.EnvironmentMetadata), global::CyberLife.Protobuff.Metadata.EnvironmentMetadata.Parser, new[]{ "MapSize", "PhenomenaMetadata" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CyberLife.Protobuff.Metadata.WorldMetadata), global::CyberLife.Protobuff.Metadata.WorldMetadata.Parser, new[]{ "EnvironmentMetadata", "LifeFormMetadata", "Name", "Age" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class StateMetadata : pb::IMessage<StateMetadata> {
    private static readonly pb::MessageParser<StateMetadata> _parser = new pb::MessageParser<StateMetadata>(() => new StateMetadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StateMetadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CyberLife.Protobuff.Metadata.MetadataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StateMetadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StateMetadata(StateMetadata other) : this() {
      name_ = other.name_;
      value_ = other.value_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StateMetadata Clone() {
      return new StateMetadata(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 2;
    private double value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StateMetadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StateMetadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Value, other.Value)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Value != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Value);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Value != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Value != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StateMetadata other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Value != 0D) {
        Value = other.Value;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 17: {
            Value = input.ReadDouble();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PhenomenMetadata : pb::IMessage<PhenomenMetadata> {
    private static readonly pb::MessageParser<PhenomenMetadata> _parser = new pb::MessageParser<PhenomenMetadata>(() => new PhenomenMetadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PhenomenMetadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CyberLife.Protobuff.Metadata.MetadataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PhenomenMetadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PhenomenMetadata(PhenomenMetadata other) : this() {
      name_ = other.name_;
      place_ = other.place_ != null ? other.place_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PhenomenMetadata Clone() {
      return new PhenomenMetadata(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "place" field.</summary>
    public const int PlaceFieldNumber = 2;
    private global::CyberLife.Protobuff.Place place_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CyberLife.Protobuff.Place Place {
      get { return place_; }
      set {
        place_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PhenomenMetadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PhenomenMetadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(Place, other.Place)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (place_ != null) hash ^= Place.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (place_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Place);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (place_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Place);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PhenomenMetadata other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.place_ != null) {
        if (place_ == null) {
          place_ = new global::CyberLife.Protobuff.Place();
        }
        Place.MergeFrom(other.Place);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (place_ == null) {
              place_ = new global::CyberLife.Protobuff.Place();
            }
            input.ReadMessage(place_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class LifeFormMetadata : pb::IMessage<LifeFormMetadata> {
    private static readonly pb::MessageParser<LifeFormMetadata> _parser = new pb::MessageParser<LifeFormMetadata>(() => new LifeFormMetadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LifeFormMetadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CyberLife.Protobuff.Metadata.MetadataReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LifeFormMetadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LifeFormMetadata(LifeFormMetadata other) : this() {
      place_ = other.place_ != null ? other.place_.Clone() : null;
      id_ = other.id_;
      statesMetadata_ = other.statesMetadata_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LifeFormMetadata Clone() {
      return new LifeFormMetadata(this);
    }

    /// <summary>Field number for the "place" field.</summary>
    public const int PlaceFieldNumber = 1;
    private global::CyberLife.Protobuff.Place place_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CyberLife.Protobuff.Place Place {
      get { return place_; }
      set {
        place_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "statesMetadata" field.</summary>
    public const int StatesMetadataFieldNumber = 3;
    private static readonly pb::FieldCodec<global::CyberLife.Protobuff.Metadata.StateMetadata> _repeated_statesMetadata_codec
        = pb::FieldCodec.ForMessage(26, global::CyberLife.Protobuff.Metadata.StateMetadata.Parser);
    private readonly pbc::RepeatedField<global::CyberLife.Protobuff.Metadata.StateMetadata> statesMetadata_ = new pbc::RepeatedField<global::CyberLife.Protobuff.Metadata.StateMetadata>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CyberLife.Protobuff.Metadata.StateMetadata> StatesMetadata {
      get { return statesMetadata_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LifeFormMetadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LifeFormMetadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Place, other.Place)) return false;
      if (Id != other.Id) return false;
      if(!statesMetadata_.Equals(other.statesMetadata_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (place_ != null) hash ^= Place.GetHashCode();
      if (Id != 0L) hash ^= Id.GetHashCode();
      hash ^= statesMetadata_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (place_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Place);
      }
      if (Id != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Id);
      }
      statesMetadata_.WriteTo(output, _repeated_statesMetadata_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (place_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Place);
      }
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      size += statesMetadata_.CalculateSize(_repeated_statesMetadata_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LifeFormMetadata other) {
      if (other == null) {
        return;
      }
      if (other.place_ != null) {
        if (place_ == null) {
          place_ = new global::CyberLife.Protobuff.Place();
        }
        Place.MergeFrom(other.Place);
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      statesMetadata_.Add(other.statesMetadata_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (place_ == null) {
              place_ = new global::CyberLife.Protobuff.Place();
            }
            input.ReadMessage(place_);
            break;
          }
          case 16: {
            Id = input.ReadInt64();
            break;
          }
          case 26: {
            statesMetadata_.AddEntriesFrom(input, _repeated_statesMetadata_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class EnvironmentMetadata : pb::IMessage<EnvironmentMetadata> {
    private static readonly pb::MessageParser<EnvironmentMetadata> _parser = new pb::MessageParser<EnvironmentMetadata>(() => new EnvironmentMetadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EnvironmentMetadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CyberLife.Protobuff.Metadata.MetadataReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnvironmentMetadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnvironmentMetadata(EnvironmentMetadata other) : this() {
      mapSize_ = other.mapSize_ != null ? other.mapSize_.Clone() : null;
      phenomenaMetadata_ = other.phenomenaMetadata_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnvironmentMetadata Clone() {
      return new EnvironmentMetadata(this);
    }

    /// <summary>Field number for the "mapSize" field.</summary>
    public const int MapSizeFieldNumber = 1;
    private global::CyberLife.Protobuff.MapSize mapSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CyberLife.Protobuff.MapSize MapSize {
      get { return mapSize_; }
      set {
        mapSize_ = value;
      }
    }

    /// <summary>Field number for the "phenomenaMetadata" field.</summary>
    public const int PhenomenaMetadataFieldNumber = 2;
    private static readonly pb::FieldCodec<global::CyberLife.Protobuff.Metadata.PhenomenMetadata> _repeated_phenomenaMetadata_codec
        = pb::FieldCodec.ForMessage(18, global::CyberLife.Protobuff.Metadata.PhenomenMetadata.Parser);
    private readonly pbc::RepeatedField<global::CyberLife.Protobuff.Metadata.PhenomenMetadata> phenomenaMetadata_ = new pbc::RepeatedField<global::CyberLife.Protobuff.Metadata.PhenomenMetadata>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CyberLife.Protobuff.Metadata.PhenomenMetadata> PhenomenaMetadata {
      get { return phenomenaMetadata_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EnvironmentMetadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EnvironmentMetadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(MapSize, other.MapSize)) return false;
      if(!phenomenaMetadata_.Equals(other.phenomenaMetadata_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (mapSize_ != null) hash ^= MapSize.GetHashCode();
      hash ^= phenomenaMetadata_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (mapSize_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MapSize);
      }
      phenomenaMetadata_.WriteTo(output, _repeated_phenomenaMetadata_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (mapSize_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MapSize);
      }
      size += phenomenaMetadata_.CalculateSize(_repeated_phenomenaMetadata_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EnvironmentMetadata other) {
      if (other == null) {
        return;
      }
      if (other.mapSize_ != null) {
        if (mapSize_ == null) {
          mapSize_ = new global::CyberLife.Protobuff.MapSize();
        }
        MapSize.MergeFrom(other.MapSize);
      }
      phenomenaMetadata_.Add(other.phenomenaMetadata_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (mapSize_ == null) {
              mapSize_ = new global::CyberLife.Protobuff.MapSize();
            }
            input.ReadMessage(mapSize_);
            break;
          }
          case 18: {
            phenomenaMetadata_.AddEntriesFrom(input, _repeated_phenomenaMetadata_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class WorldMetadata : pb::IMessage<WorldMetadata> {
    private static readonly pb::MessageParser<WorldMetadata> _parser = new pb::MessageParser<WorldMetadata>(() => new WorldMetadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WorldMetadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CyberLife.Protobuff.Metadata.MetadataReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WorldMetadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WorldMetadata(WorldMetadata other) : this() {
      environmentMetadata_ = other.environmentMetadata_ != null ? other.environmentMetadata_.Clone() : null;
      lifeFormMetadata_ = other.lifeFormMetadata_.Clone();
      name_ = other.name_;
      age_ = other.age_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WorldMetadata Clone() {
      return new WorldMetadata(this);
    }

    /// <summary>Field number for the "environmentMetadata" field.</summary>
    public const int EnvironmentMetadataFieldNumber = 1;
    private global::CyberLife.Protobuff.Metadata.EnvironmentMetadata environmentMetadata_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CyberLife.Protobuff.Metadata.EnvironmentMetadata EnvironmentMetadata {
      get { return environmentMetadata_; }
      set {
        environmentMetadata_ = value;
      }
    }

    /// <summary>Field number for the "LifeFormMetadata" field.</summary>
    public const int LifeFormMetadataFieldNumber = 2;
    private static readonly pbc::MapField<long, global::CyberLife.Protobuff.Metadata.LifeFormMetadata>.Codec _map_lifeFormMetadata_codec
        = new pbc::MapField<long, global::CyberLife.Protobuff.Metadata.LifeFormMetadata>.Codec(pb::FieldCodec.ForInt64(8), pb::FieldCodec.ForMessage(18, global::CyberLife.Protobuff.Metadata.LifeFormMetadata.Parser), 18);
    private readonly pbc::MapField<long, global::CyberLife.Protobuff.Metadata.LifeFormMetadata> lifeFormMetadata_ = new pbc::MapField<long, global::CyberLife.Protobuff.Metadata.LifeFormMetadata>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<long, global::CyberLife.Protobuff.Metadata.LifeFormMetadata> LifeFormMetadata {
      get { return lifeFormMetadata_; }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "age" field.</summary>
    public const int AgeFieldNumber = 4;
    private int age_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Age {
      get { return age_; }
      set {
        age_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WorldMetadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WorldMetadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(EnvironmentMetadata, other.EnvironmentMetadata)) return false;
      if (!LifeFormMetadata.Equals(other.LifeFormMetadata)) return false;
      if (Name != other.Name) return false;
      if (Age != other.Age) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (environmentMetadata_ != null) hash ^= EnvironmentMetadata.GetHashCode();
      hash ^= LifeFormMetadata.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Age != 0) hash ^= Age.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (environmentMetadata_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(EnvironmentMetadata);
      }
      lifeFormMetadata_.WriteTo(output, _map_lifeFormMetadata_codec);
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Age != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Age);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (environmentMetadata_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EnvironmentMetadata);
      }
      size += lifeFormMetadata_.CalculateSize(_map_lifeFormMetadata_codec);
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Age != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Age);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WorldMetadata other) {
      if (other == null) {
        return;
      }
      if (other.environmentMetadata_ != null) {
        if (environmentMetadata_ == null) {
          environmentMetadata_ = new global::CyberLife.Protobuff.Metadata.EnvironmentMetadata();
        }
        EnvironmentMetadata.MergeFrom(other.EnvironmentMetadata);
      }
      lifeFormMetadata_.Add(other.lifeFormMetadata_);
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Age != 0) {
        Age = other.Age;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (environmentMetadata_ == null) {
              environmentMetadata_ = new global::CyberLife.Protobuff.Metadata.EnvironmentMetadata();
            }
            input.ReadMessage(environmentMetadata_);
            break;
          }
          case 18: {
            lifeFormMetadata_.AddEntriesFrom(input, _map_lifeFormMetadata_codec);
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 32: {
            Age = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
